apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-advanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-advanced
  template:
    metadata:
      labels:
        app: demo-advanced
    spec:
      containers:
      - name: alpine 
        image: ghcr.io/linuxcontainers/alpine:placeholder
        command: ["sleep", "infinity"]
