apiVersion: v1
kind: Service
metadata:
  name: demo-advanced
spec:
  type: NodePort
  selector:
    app: demo-advanced
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: placeholder
