apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-basic
  template:
    metadata:
      labels:
        app: demo-basic
    spec:
      containers:
      - name: nginx 
        image: nginx:placeholder
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: content
        configMap:
          name: demo-basic-content
