apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-basic
  template:
    metadata:
      labels:
        app: demo-basic
    spec:
      containers:
      - name: alpine 
        image: alpine:placeholder
