apiVersion: v1
kind: Service
metadata:
  name: demo-basic
spec:
  type: NodePort
  selector:
    app: demo-basic
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: placeholder
